<?php

use Elasticsearch\ClientBuilder;

/**
 * Display help and module information
 * @return help text for section
 */
function arborelastic_help($path, $arg) {
  $output = '';

  switch ($path) {
    case "admin/help#arborelastic":
      $output = '<p>' .  t("Custom search with Elasticsearch") . '</p>';
      break;
  }

  return $output;
}

function arborelastic_search($path_id, $query, $args = []) {
  $indexes = \Drupal::config('arborelastic.settings')->get('arborelastic_indexes');
  $indexes = explode("\n", $indexes);
  foreach ($indexes as $i => $index) {
    $parts = explode(':', $index);
    $indexes[$parts[0]] = array('index' => $parts[1], 'type' => $parts[2]);
    unset($indexes[$i]);
  }

  $hosts = [
    [
      'host' => \Drupal::config('arborelastic.settings')->get('arborelastic_host'),
      'port' => \Drupal::config('arborelastic.settings')->get('arborelastic_port'),
      'user' => \Drupal::config('arborelastic.settings')->get('arborelastic_user'),
      'pass' => \Drupal::config('arborelastic.settings')->get('arborelastic_pass'),
    ]
  ];

  $es_client = ClientBuilder::create()->setHosts($hosts)->build();

  $es_query = [
    'bool' => [
      'must' => [
        ['match' => ['_all' => $query] ],
      ],
    ]
  ];

  $size = 25;
  $from = 0;
  foreach ($args as $field => $value) {
    if ($field == 'size') {
      $size = $value;
    } elseif ($field == 'page') {
      $from = $_GET['page'];
    } else {
      if ($field != 'gridview') {
        $values = explode(',', $value);
        $es_query['bool']['must'][] = ['terms' => [$field => $values]];
      }
    }
  }

  $params = [
      'index' => $indexes[$path_id]['index'],
      'from' => $from,
      'body' => [
        'size' => $size,
        'query' => $es_query,
        'aggs' => [
          'mat_code' => [
            'terms' => [
              'field' => 'mat_code.keyword'
            ]
          ]
        ]
      ]
  ];

  return $es_client->search($params);
}

function arborelastic_theme($existing, $type, $theme, $path) {
  return [
    'search_results' => [
      'variables' => [
        'api_key' => NULL,
        'lists' => NULL,
        'results' => NULL,
        'facets' => NULL,
        'gridview' => NULL
      ]
    ]
  ];
}
