<?php

use Elasticsearch\ClientBuilder;

/**
 * Display help and module information
 * @return help text for section
 */

function arborelastic_help($path, $arg)
{
  $output = '';
  switch ($path) {
    case "admin/help#arborelastic":
      $output = '<p>' .  t("Custom search with Elasticsearch") . '</p>';
      break;
  }
  return $output;
}
function arborelastic_theme($existing, $theme, $path)
{
  return [
    'search_results' => [
      'variables' => [
        'path_id' => NULL,
        'api_key' => NULL,
        'lists' => NULL,
        'results' => NULL,
        'facets' => NULL,
        'gridview' => NULL,
        'pager' => NULL
      ]
    ]
  ];
}
